// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto-prod-testing/logcentral_logs.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VectorLogs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Ddtags        map[string]string      `protobuf:"bytes,2,rep,name=ddtags,proto3" json:"ddtags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Env           string                 `protobuf:"bytes,4,opt,name=env,proto3" json:"env,omitempty"`
	ServiceName   string                 `protobuf:"bytes,5,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ComponentName string                 `protobuf:"bytes,6,opt,name=component_name,json=componentName,proto3" json:"component_name,omitempty"`
	Hostname      *string                `protobuf:"bytes,7,opt,name=hostname,proto3,oneof" json:"hostname,omitempty"`
	Ddsource      *string                `protobuf:"bytes,8,opt,name=ddsource,proto3,oneof" json:"ddsource,omitempty"`
	SourceType    *string                `protobuf:"bytes,9,opt,name=source_type,json=sourceType,proto3,oneof" json:"source_type,omitempty"`
	Status        *string                `protobuf:"bytes,10,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Extra         map[string]string      `protobuf:"bytes,11,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorLogs) Reset() {
	*x = VectorLogs{}
	mi := &file_proto_prod_testing_logcentral_logs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorLogs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorLogs) ProtoMessage() {}

func (x *VectorLogs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_prod_testing_logcentral_logs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorLogs.ProtoReflect.Descriptor instead.
func (*VectorLogs) Descriptor() ([]byte, []int) {
	return file_proto_prod_testing_logcentral_logs_proto_rawDescGZIP(), []int{0}
}

func (x *VectorLogs) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VectorLogs) GetDdtags() map[string]string {
	if x != nil {
		return x.Ddtags
	}
	return nil
}

func (x *VectorLogs) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *VectorLogs) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *VectorLogs) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *VectorLogs) GetComponentName() string {
	if x != nil {
		return x.ComponentName
	}
	return ""
}

func (x *VectorLogs) GetHostname() string {
	if x != nil && x.Hostname != nil {
		return *x.Hostname
	}
	return ""
}

func (x *VectorLogs) GetDdsource() string {
	if x != nil && x.Ddsource != nil {
		return *x.Ddsource
	}
	return ""
}

func (x *VectorLogs) GetSourceType() string {
	if x != nil && x.SourceType != nil {
		return *x.SourceType
	}
	return ""
}

func (x *VectorLogs) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *VectorLogs) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

var File_proto_prod_testing_logcentral_logs_proto protoreflect.FileDescriptor

const file_proto_prod_testing_logcentral_logs_proto_rawDesc = "" +
	"\n" +
	"(proto-prod-testing/logcentral_logs.proto\x12\x0flogcentral.logs\x1a\x1fgoogle/protobuf/timestamp.proto\"\xea\x04\n" +
	"\n" +
	"VectorLogs\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12?\n" +
	"\x06ddtags\x18\x02 \x03(\v2'.logcentral.logs.VectorLogs.DdtagsEntryR\x06ddtags\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x10\n" +
	"\x03env\x18\x04 \x01(\tR\x03env\x12!\n" +
	"\fservice_name\x18\x05 \x01(\tR\vserviceName\x12%\n" +
	"\x0ecomponent_name\x18\x06 \x01(\tR\rcomponentName\x12\x1f\n" +
	"\bhostname\x18\a \x01(\tH\x00R\bhostname\x88\x01\x01\x12\x1f\n" +
	"\bddsource\x18\b \x01(\tH\x01R\bddsource\x88\x01\x01\x12$\n" +
	"\vsource_type\x18\t \x01(\tH\x02R\n" +
	"sourceType\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\n" +
	" \x01(\tH\x03R\x06status\x88\x01\x01\x12<\n" +
	"\x05extra\x18\v \x03(\v2&.logcentral.logs.VectorLogs.ExtraEntryR\x05extra\x1a9\n" +
	"\vDdtagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\v\n" +
	"\t_hostnameB\v\n" +
	"\t_ddsourceB\x0e\n" +
	"\f_source_typeB\t\n" +
	"\a_statusB+\n" +
	"\x14com.dream11.protobufP\x01Z\x11livelogs/protobufb\x06proto3"

var (
	file_proto_prod_testing_logcentral_logs_proto_rawDescOnce sync.Once
	file_proto_prod_testing_logcentral_logs_proto_rawDescData []byte
)

func file_proto_prod_testing_logcentral_logs_proto_rawDescGZIP() []byte {
	file_proto_prod_testing_logcentral_logs_proto_rawDescOnce.Do(func() {
		file_proto_prod_testing_logcentral_logs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_prod_testing_logcentral_logs_proto_rawDesc), len(file_proto_prod_testing_logcentral_logs_proto_rawDesc)))
	})
	return file_proto_prod_testing_logcentral_logs_proto_rawDescData
}

var file_proto_prod_testing_logcentral_logs_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_prod_testing_logcentral_logs_proto_goTypes = []any{
	(*VectorLogs)(nil),            // 0: logcentral.logs.VectorLogs
	nil,                           // 1: logcentral.logs.VectorLogs.DdtagsEntry
	nil,                           // 2: logcentral.logs.VectorLogs.ExtraEntry
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_proto_prod_testing_logcentral_logs_proto_depIdxs = []int32{
	1, // 0: logcentral.logs.VectorLogs.ddtags:type_name -> logcentral.logs.VectorLogs.DdtagsEntry
	3, // 1: logcentral.logs.VectorLogs.timestamp:type_name -> google.protobuf.Timestamp
	2, // 2: logcentral.logs.VectorLogs.extra:type_name -> logcentral.logs.VectorLogs.ExtraEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_prod_testing_logcentral_logs_proto_init() }
func file_proto_prod_testing_logcentral_logs_proto_init() {
	if File_proto_prod_testing_logcentral_logs_proto != nil {
		return
	}
	file_proto_prod_testing_logcentral_logs_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_prod_testing_logcentral_logs_proto_rawDesc), len(file_proto_prod_testing_logcentral_logs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_prod_testing_logcentral_logs_proto_goTypes,
		DependencyIndexes: file_proto_prod_testing_logcentral_logs_proto_depIdxs,
		MessageInfos:      file_proto_prod_testing_logcentral_logs_proto_msgTypes,
	}.Build()
	File_proto_prod_testing_logcentral_logs_proto = out.File
	file_proto_prod_testing_logcentral_logs_proto_goTypes = nil
	file_proto_prod_testing_logcentral_logs_proto_depIdxs = nil
}
